import type { EvidenceRecord, Issue } from './types'

const commonHistory = (title: string, creator = '李予 / 审核员') => [
  { at: '09-22 10:35', actor: creator, action: '创建问题', detail: `录入 ${title}，并关联页面录屏。` },
  { at: '09-24 16:10', actor: '系统', action: '根因聚类', detail: '与同类问题合并，保留子问题追溯关系。' },
]

export const seedIssues: Issue[] = [
  {
    key: 'A11Y-1048',
    title: '商品筛选抽屉无法通过键盘关闭',
    site: '商城 Web',
    version: 'v4.18',
    wcag: ['2.1.2 无键盘陷阱', '2.1.1 键盘'],
    issueType: '键盘操作',
    impact: '致命',
    affected: '筛选面板 / 移动端与桌面键盘用户',
    reproduction: '打开商品筛选抽屉，使用 Tab 遍历后按 Esc，焦点仍循环在抽屉内部。',
    evidence: 'https://evidence.example.com/a11y-1048',
    rootCause: '共用 Drawer 组件缺少 focus trap 退出逻辑',
    status: '修复中',
    priority: 'P0',
    team: '前端基础组件组',
    owner: '何沐',
    dueDate: '2026-10-06',
    mergedKeys: ['A11Y-1052', 'A11Y-1061'],
    createdBy: '李予',
    createdByRole: '审核员',
    retestRecords: [],
    history: commonHistory('筛选抽屉键盘陷阱'),
  },
  {
    key: 'A11Y-1052',
    title: '客服弹窗焦点无法返回触发按钮',
    site: '商城 Web',
    version: 'v4.18',
    wcag: ['2.4.3 焦点顺序'],
    issueType: '焦点管理',
    impact: '严重',
    affected: '客服入口 / 所有键盘用户',
    reproduction: '打开客服弹窗，关闭后焦点落到 body。',
    evidence: 'https://evidence.example.com/a11y-1052',
    rootCause: '共用 Drawer 组件缺少 focus trap 退出逻辑',
    status: '已通过',
    priority: 'P1',
    team: '前端基础组件组',
    owner: '何沐',
    dueDate: '2026-10-03',
    mergedKeys: [],
    createdBy: '李予',
    createdByRole: '审核员',
    fixNote: '增加关闭后的 triggerRef.focus 恢复逻辑。',
    fixer: '何沐',
    retestEnv: 'Chrome 140 / VoiceOver / 商城 v4.18.3',
    retestEnvVersion: 'v4.18',
    retestEnvAt: '2026-09-28',
    retester: '苏禾',
    retestRecords: [
      {
        id: 'RT-22',
        actor: '苏禾',
        actorRole: '复测员',
        result: '通过',
        note: '焦点返回触发按钮，顺序正确。',
        at: '09-28 14:20',
        evidenceVersion: 'v4.18',
        evidenceHash: 'h-1052-20260910',
        valid: true,
      },
    ],
    history: commonHistory('客服弹窗焦点恢复'),
  },
  {
    key: 'A11Y-1061',
    title: '优惠券选择层存在键盘循环',
    site: '会员中心',
    version: 'v3.9',
    wcag: ['2.1.2 无键盘陷阱'],
    issueType: '键盘操作',
    impact: '严重',
    affected: '结算券选择 / 键盘用户',
    reproduction: 'Shift+Tab 超过首元素后焦点进入不可见元素。',
    evidence: 'https://evidence.example.com/a11y-1061',
    rootCause: '共用 Drawer 组件缺少 focus trap 退出逻辑',
    status: '待分配',
    priority: 'P1',
    team: '结算体验组',
    owner: '待分配',
    dueDate: '2026-10-10',
    mergedKeys: [],
    createdBy: '李予',
    createdByRole: '审核员',
    retestRecords: [],
    history: commonHistory('优惠券选择层键盘循环'),
  },
  {
    key: 'A11Y-1074',
    title: '数据图表颜色对比度不足',
    site: '运营后台',
    version: 'v2.7',
    wcag: ['1.4.11 非文本对比度', '1.4.3 对比度'],
    issueType: '视觉对比',
    impact: '中等',
    affected: '经营趋势图 / 低视力用户',
    reproduction: '趋势线 3 与背景对比度约 2.6:1。',
    evidence: 'https://evidence.example.com/a11y-1074',
    rootCause: '图表主题色板未执行无障碍校验',
    status: '待复测',
    priority: 'P2',
    team: '数据可视化组',
    owner: '赵屿',
    dueDate: '2026-10-09',
    mergedKeys: [],
    createdBy: '李予',
    createdByRole: '审核员',
    fixNote: '更换色板并增加虚线纹理和可切换数据表。',
    fixer: '赵屿',
    retestEnv: 'Safari 26 / 对比度工具 / admin-v2.7.5',
    retestEnvVersion: 'v2.7',
    retestEnvAt: '2026-10-02',
    retestRecords: [],
    history: commonHistory('图表颜色对比度'),
  },
  {
    key: 'A11Y-1083',
    title: '表单错误提示未被读屏软件播报',
    site: '采购门户',
    version: 'v1.12',
    wcag: ['3.3.1 错误识别', '4.1.3 状态消息'],
    issueType: '错误提示',
    impact: '严重',
    affected: '供应商注册表单 / 屏幕阅读器用户',
    reproduction: '填写无效税号并提交，视觉提示出现但无 live region。',
    evidence: 'https://evidence.example.com/a11y-1083',
    rootCause: '表单错误组件未接入 aria-live 和字段描述',
    status: '已退回',
    priority: 'P1',
    team: '供应链前端组',
    owner: '顾雪',
    dueDate: '2026-10-05',
    mergedKeys: [],
    createdBy: '李予',
    createdByRole: '审核员',
    fixNote: '计划仅增加视觉错误颜色。',
    fixer: '顾雪',
    retestRecords: [
      {
        id: 'RT-31',
        actor: '李予',
        actorRole: '审核员',
        result: '退回',
        note: '仍需接入 aria-live，并验证字段 aria-describedby。',
        at: '09-28 11:05',
        valid: false,
        invalidReason: '非复测员判定',
      },
    ],
    history: commonHistory('表单错误提示'),
  },
  {
    key: 'A11Y-1092',
    title: '后台侧边栏展开后焦点未锁定',
    site: '运营后台',
    version: 'v2.7',
    wcag: ['2.1.2 无键盘陷阱'],
    issueType: '键盘操作',
    impact: '严重',
    affected: '运营后台侧边栏 / 键盘用户',
    reproduction: '侧边栏展开后 Tab 焦点逸出到主内容区。',
    evidence: 'https://evidence.example.com/a11y-1092',
    rootCause: '侧边栏容器缺少焦点捕获',
    status: '已通过',
    priority: 'P2',
    team: '数据可视化组',
    owner: '赵屿',
    dueDate: '2026-09-20',
    mergedKeys: [],
    createdBy: '李予',
    createdByRole: '审核员',
    retestEnv: 'Chrome 138 / admin-v2.6.0',
    retestEnvVersion: 'v2.6',
    retestEnvAt: '2026-08-10',
    retestRecords: [],
    history: commonHistory('后台侧边栏焦点锁定'),
  },
]

/** 外部证据注册表：版本对不上就重算，证据一变结论立即失效 */
export const seedEvidence: EvidenceRecord[] = [
  { url: 'https://evidence.example.com/a11y-1048', version: 'v4.19', hash: 'h-1048-20260930', updatedAt: '2026-09-30' },
  { url: 'https://evidence.example.com/a11y-1052', version: 'v4.18', hash: 'h-1052-20260918', updatedAt: '2026-09-18' },
  { url: 'https://evidence.example.com/a11y-1061', version: 'v3.9', hash: 'h-1061-20260915', updatedAt: '2026-09-15' },
  { url: 'https://evidence.example.com/a11y-1074', version: 'v2.7', hash: 'h-1074-20260922', updatedAt: '2026-09-22' },
  { url: 'https://evidence.example.com/a11y-1083', version: 'v1.12', hash: 'h-1083-20260928', updatedAt: '2026-09-28' },
  // a11y-1092 证据缺失，整批对账将失败
]
